// =============================================================
//  words.js — Base de palabras para WORDLE ES
//
//  DAILY_WORDS : palabras que se usarán como solución diaria
//                (en orden cronológico desde START_DATE)
//
//  VALID_WORDS : palabras válidas para las comprobaciones
//                (se incluyen automáticamente las DAILY_WORDS)
//
//  ► CÓMO AÑADIR TUS PROPIAS PALABRAS DIARIAS:
//    1. Abre este archivo.
//    2. Añade tus palabras al array DAILY_WORDS (5 letras, mayúsculas).
//    3. Ajusta START_DATE a la fecha del primer elemento del array.
//    4. ¡Listo! El juego seleccionará una palabra distinta cada día.
// =============================================================

const START_DATE = "2025-01-01"; // ← Fecha de la primera palabra del array

// Palabras diarias — añade, quita o reordena a tu gusto
const DAILY_WORDS = [
  "CAMPO", "GATOS", "PLAYA", "TABLA", "FLOTA",
  "GLOBO", "LIBRO", "NOCHE", "PARED", "SILLA",
  "BRISA", "CARTA", "DUELO", "ESCENA","FERIA",
  "GRUTA", "HUESO", "IGLÉS","JOVEN", "KARMA",
  "LIMON", "MARCA", "NIEVE", "ORDEN", "PATIO",
  "QUESO", "RATON", "SABOR", "TIGRE", "UMBRA",
  "VALOR", "WORLD", "XENON", "YARDA", "ZUMOS",
  "ABEJA", "BOTÓN", "CACAO", "DANZA", "ESPÍN",
  "FALDA", "GALIO", "HABLA", "INDIO", "JUSTO",
  "KOALA", "LAPIZ", "MUSGO", "NARIZ", "OLIVA",
  "PALMA", "QATAR", "RADAR", "SALSA", "TECHO",
  "ÚNICO", "VAPOR", "WAFER", "XEROX", "YOGUR",
  "ZARZA", "AGUJA", "BARRO", "CASPA", "DEBIL",
  "ENERO", "FAROL", "GAMBA", "HORDA", "IMPAR",
  "JEREZ", "KIWIS", "LINCE", "MESTO", "NOVIO",
  "OREJA", "PLAZA", "QUEJA", "REBAÑ","SUELA",
  "TUNEL", "URNAS", "VIEJO", "ZURDA", "AMIGA",
  "BANCO", "CISNE", "DIETA", "ESTRO", "FIDEO",
  "GORDO", "HIELO", "ICONO", "JAULA", "LABIA",
  "MEDAL", "NEGRO", "OCHOA", "PULPO", "RISCO",
  // ► Añade más palabras aquí ↓
];

// Vocabulario completo para validar intentos (mínimo ~2000 palabras)
// Puedes ampliar esta lista con más palabras válidas del español
const VALID_WORDS_EXTRA = [
  "AADIR","ABADA","ABAJO","ABANA","ABAÑO","ABASE","ABATE","ABDAL","ABEJA",
  "ABOBO","ABOCO","ABOGA","ABONO","ABRIR","ABUSO","ACABO","ACASO","ACATA",
  "ACEBO","ACEDO","ACERO","ACETO","ACIAL","ACIDA","ACODO","ACOGE","ACORO",
  "ACRES","ACTUA","ACUDE","ACUÑA","ADAMA","ADEJA","ADEMA","ADENA","ADERE",
  "ADIAR","ADOBA","ADOLA","ADONA","ADORE","ADORO","ADOSA","ADUCE","ADULO",
  "AFACA","AFAMA","AFEAR","AFINE","AFINO","AFITA","AFOGA","AGACE","AGAMO",
  "AGAPE","AGARR","AGATA","AGAVE","AGITA","AGOTA","AGUAS","AGUDO","AGUJA",
  "AHIJA","AHILA","AHITO","AHOGA","AHORA","AHUMA","AIRAR","AIREO","AIROS",
  "AJADA","AJADO","AJENO","AJIMU","AJUAR","AJUMA","AJUNO","ALABA","ALADA",
  "ALADO","ALAGA","ALAMA","ALAMO","ALANO","ALARM","ALAZA","ALBAS","ALCEA",
  "ALCEO","ALDEA","ALEJA","ALELO","ALETO","ALFAR","ALGAS","ALGOS","ALIAR",
  "ALOJA","ALONA","ALOSA","ALOYA","ALOZA","ALTAR","ALTEA","ALTER","ALTEZ",
  "ALTOR","ALTURA","ALUDA","ALULO","ALUNA","ALUNO","ALVAR","ALZAR","AMABA",
  "AMAGO","AMAGO","AMARA","AMASE","AMASA","AMAZA","AMBAR","AMBAS","AMIGA",
  "AMIGO","AMITO","AMONA","AMONO","AMOR","AMPLA","AMPLO","AMPRA","AMURA",
  "AMUSO","ANACO","ANADA","ANAHO","ANAJA","ANANA","ANATA","ANCHO","ANCIA",
  "ANCLA","ANCON","ANDAS","ANDAR","ANDEZ","ANDRE","ANDUR","ANEJO","ANGEL",
  "ANGLA","ANGRA","ANGRO","ANHOS","ANIDA","ANIMA","ANIME","ANIMO","ANION",
  "ANISA","ANISO","ANITA","ANITO","ANOAS","ANOHA","ANTES","ANUAL","AÑADE",
  "AÑEJA","AÑEJO","AÑUDA","APAGA","APAGO","APARA","APARE","APARO","APATA",
  "APEAR","APELA","APERO","APERS","APILA","APILO","APIÑA","APIÑO","APIÑA",
  "APOCA","APOCO","APODA","APODO","APOGA","APOGO","APOLA","APOLO","APORA",
  "APORO","APOSA","APOSO","APOYA","APOYO","APROA","APROE","APURO","ARABE",
  "ARADA","ARADO","ARANA","ARANE","ARAÑO","ARAZA","ARBOR","ARCAZ","ARCEA",
  "ARCOS","ARDEA","ARDUO","ARENA","ARENO","ARETE","ARFAR","ARGOT","ARIDA",
  "ARIDO","ARIEL","ARIJO","ARILO","ARIMA","ARIMO","ARJON","ARLES","ARMAR",
  "ARMAS","ARMEN","ARMIO","ARMON","AROMA","AROMO","ARPIA","ARPON","ARRAS",
  "ARROZ","ARTAL","ARTES","ASADA","ASADO","ASEAR","ASEDO","ASESO","ASINO",
  "ASION","ASIRA","ASIRO","ASNAR","ASOMA","ASOMO","ASPID","ASTRO","ASTUR",
  "ATABA","ATADO","ATAJA","ATAJE","ATAJO","ATALA","ATALO","ATAMA","ATAMO",
  "ATAÑO","ATARE","ATARÉ","ATASE","ATESA","ATIBA","ATIBO","ATIBO","ATILA",
  "ATILO","ATINA","ATINO","ATIPA","ATIPO","ATIZA","ATIZO","ATOLE","ATONA",
  "ATONO","ATORA","ATORO","ATOZA","ATRÁS","ATRIL","ATUNO","AUDAZ","AUDIO",
  "AUDIT","AULAS","AVADO","AVAHO","AVALA","AVALO","AVARO","AVENA","AVISO",
  "AVOCA","AVOCO","AVUDA","AXIAL","AYUDA","AZADA","AZNAR","AZORA","AZOTE",
  "AZOTO","AZUCAR","AZUDA","AZULA","AZULO","AZURA","AZURO","BACHE","BADAR",
  "BADEA","BADIA","BAHIA","BAILE","BAJAR","BAJEL","BAJON","BALAR","BALDO",
  "BAMBA","BANCO","BANDA","BAÑAR","BAÑOS","BARCA","BARCO","BARIO","BARRA",
  "BARRO","BASAR","BASCA","BASTE","BASTO","BATAN","BATIR","BATUTA","BAÚL",
  "BAYOS","BEBER","BEIGE","BELÉN","BELLO","BESAR","BIELA","BIRRA","BISTÉ",
  "BIZCO","BOCAS","BOLOS","BOLSA","BOMBA","BONDI","BORDE","BORDO","BORLA",
  "BOSCO","BOTAR","BOTON","BOXEO","BRAGA","BROMA","BROTE","BRUJA","BUCHE",
  "BUENA","BUFÓN","BUQUE","CABAL","CABRA","CACAO","CACAO","CACHA","CACHO",
  "CADIZ","CAÍDA","CALAR","CALCO","CALDO","CALOR","CALVA","CALVO","CAMBO",
  "CAMEO","CANON","CAOBA","CAPAZ","CAPOS","CAPÓN","CARGA","CARGO","CARPA",
  "CARRO","CASCO","CASPA","CATAR","CAUCE","CAVAR","CAVIA","CAYDO","CAZAR",
  "CEBRA","CEJAR","CENAR","CEÑIR","CERCA","CERCO","CESAR","CICLO","CIELO",
  "CITAR","CLARO","CLAVE","CLAVO","COBRO","COCOA","COFRE","COGER","COIMA",
  "COITO","COJER","COJON","COLLAR","COMBO","COMET","CONDA","COPAL","CORMO",
  "CORTO","CORVO","COSTA","COSTE","CREMA","CUADRO","CUAJO","CUBIL","CUERO",
  "CUEVA","CUOTA","CURVA","DARDO","DATAR","DEBUT","DEDAL","DELCO","DENSO",
  "DEPRE","DERBY","DICHA","DICHO","DIQUE","DISCO","DOBLO","DOLOR","DONAR",
  "DOTAR","DULCE","DUNAR","DURAR","EBRIO","EDEMA","EGIDA","EJOTE","EMBAR",
  "EMOJI","EMPAP","ENANO","ENCÍA","ENOJO","ENOJO","EQUIS","ERGIR","ERIZO",
  "ERROR","ESCAJ","ESLÓN","ESMOG","ESPÍA","ESTÉO","ETAPA","ETNIA","EVOCO",
  "EXIGE","EXITO","EXTRA","FÁBLA","FABIO","FACÓN","FALAZ","FALLO","FANGO",
  "FARSA","FAVOR","FECHA","FÉFOL","FEROZ","FIBRA","FIERA","FIJEZ","FINAL",
  "FIRMA","FÍSICA","FISCO","FLECO","FLEXA","FLIRT","FLOJO","FLORA","FLUIR",
  "FOLIO","FONDO","FORMA","FORRO","FOSIL","FRAGA","FRASE","FREÍR","FRENO",
  "FRUTA","FUEGO","FURIA","FUSIL","GAFAS","GALAN","GANAS","GARBO","GARZA",
  "GASTO","GENIO","GIRAR","GOLPE","GORDO","GRAMO","GRAVE","GRIAL","GRIPE",
  "GRUTA","GUAPO","GUIÓN","GUISA","GUSTO","HABLA","HACHA","HARINA","HARPA",
  "HEBRA","HELIO","HERPE","HEXAL","HILAR","HIMNO","HIPNO","HOCIO","HONDO",
  "HONRA","HUESO","HUMOR","ICONO","IDIOM","IGUAL","IMAGO","IMPAR","IMPÍO",
  "INCOA","INDIO","INDOL","INEMA","INFRA","INGRA","INOPE","INTER","INTRO",
  "IRULA","JABÓN","JALAR","JAMÓN","JAULA","JETAR","JORAR","JOSCO","JOULE",
  "JUEGO","JUGÓN","JURAR","JUTÍA","LABIA","LABIO","LABOR","LACRA","LAICO",
  "LAMER","LANCE","LANZA","LARGO","LASER","LAÚD","LAZOS","LEGAL","LETAL",
  "LIBAR","LIBRA","LIEBRE","LIGAR","LINFA","LLAGA","LLAMA","LLANO","LLENO",
  "LLEVO","LOBBY","LOGIO","LOGRO","LÓBUL","LUCIO","LUCHA","LUNAR","MANGA",
  "MANSO","MANTA","MANTO","MAÑANA","MAPAR","MAREO","MAFIA","MALÓN","MANTO",
  "MASCA","MASÓN","MÉDIO","MEDRA","MELLA","MENOR","MENTA","MENOS","METRO",
  "MIEDO","MIGAS","MIRAR","MÍSERO","MITAD","MITRA","MÓBIL","MOCHO","MOGOL",
  "MOHÍN","MOJAR","MOLDE","MOLER","MONCO","MORBO","MORSA","MOTEL","MUECA",
  "MUSLO","NADAR","NARCO","NARIZ","NATAL","NEGRA","NEGRO","NORMA","OASIS",
  "OBESO","OBRAR","OCASO","OCTAL","ODIAR","OFRÉZ","OIDOR","OJEAR","OMEGA",
  "ONION","OPACO","OPERA","OPTIO","OREJA","ORGÍA","ORUGA","OTROS","OVEJA",
  "PACOS","PAJAR","PALCO","PALMA","PAPAL","PARCO","PARTE","PASAR","PASTA",
  "PATÍN","PATIO","PÁJARO","PECIO","PEDAL","PERLA","PERRA","PICAR","PICO",
  "PILAR","PINTA","PISAR","PISTA","PLAGA","PLANA","PLOMO","PODAR","PODER",
  "POLVO","POMPA","PORRA","PORTE","PRISA","PROFE","PROLE","PRONE","PROSA",
  "PUCHA","PUNAL","PUPIL","QUEBR","QUESO","QUIDO","QUIMO","QUITA","RACIO",
  "RALEO","RAMAS","RAMPA","RASGO","RAYAR","RAZIO","REBAB","RECTA","REGIO",
  "REINA","RELOJ","RENCA","RIGOR","ROBLO","RONCO","RONIN","ROSCA","RUBIO",
  "RUGIR","RUIDO","RUSCO","SABER","SALIR","SALMO","SALTO","SALUD","SALVO",
  "SANOS","SASTRE","SABER","SELVA","SEÑAL","SEPIA","SERBO","SEXTO","SILLA",
  "SOLAR","SOLDO","SONDO","SONÁR","SOPIA","SORDO","SUAVE","SUECO","SUSTO",
  "TABLA","TALAR","TALCO","TALDO","TALLO","TAMIZ","TAPÓN","TARRO","TELAR",
  "TIESO","TILDE","TINTE","TIRAS","TIRAR","TOCAR","TORPE","TORTA","TUTOR",
  "ULTRA","UMBRA","UNGIR","ÚNICO","UNTAR","URANO","VACUO","VAPOR","VARIO",
  "VELOZ","VENAL","VERBO","VERDE","VIAJA","VICIO","VIGOR","VIOLA","VIRAL",
  "VISTA","VITAL","VIUDA","VOCAL","VORAZ","VULGO","XILOL","YACER","YARDA",
  "YERBA","YUGOS","ZAMPA","ZARCO","ZOCLO","ZORRO","ZUMOS",
];

// Une las dos listas para validación
const ALL_VALID_WORDS = [...new Set([...DAILY_WORDS, ...VALID_WORDS_EXTRA])];
